### ISSUE TITLE
使用compose挂载本地目录时，遇到错误

### ISSUE THREAD

**Issue by lin0kin** [dream10201/115Docker#23]
在飞牛中运行时，将目录挂载至nfs加载的硬盘时，容器内报错，不挂载目录就可以正常运行，错误如下：

```text
tint2: Using glib slice allocator (default). Run tint2 with environment variable G_SLICE=always-malloc in case of strange behavior or crashes

tint2: could not open display!
```

转换的compose命令为：

```yml
services:
  115browser:
    image: docker.io/xiuxiu10201/115:latest
    container_name: 115browser
    user: 0:0
    ports:
      - 41150:1150
    volumes:
      - /vol1/1000/docker/115browser:/etc/115
      - /vol02/1000-0-9287bf42/video:/opt/Downloads
    environment:
      - PASSWORD=123456
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - TZ=Asia/Shanghai
      - G_SLICE=always-malloc
```
